name: Frontend CD Pipeline

on:
  pull_request:
    branches:
      - main
    types: [closed]
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to Oracle Cloud VM
        uses: appleboy/ssh-action@master
        timeout-minutes: 20
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_KEY }}
          script: |
            cd /home/***/weaver/SA-Front

            sudo git pull origin main

            sudo docker build -t salk1104/front:latest .
            sudo docker push salk1104/front
            
            sudo docker stack rm weaver
            sudo docker stack deploy -c ../docker-compose.yml weaver
